# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReadOnlySwitcher
                                 A QGIS plugin
 Read-Only Switcher lets you toggle the read-only flag for one or more selected layers directly from the Layers panel, saving you the step of opening Project Properties.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-09
        copyright            : (C) 2025 by Lei Ding
        email                : lleidding@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ReadOnlySwitcher class from file ReadOnlySwitcher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .read_only_switcher import ReadOnlySwitcher
    return ReadOnlySwitcher(iface)
